### ISSUE TITLE
`numpy.AxisError: axis 3 is out of bounds for array of dimension 3`

### ISSUE THREAD

**Issue by aksub99** [ktm2/ImageDataExtractor#2]
Hi,
Thanks for the great work!
I installed ImageDataExtractor with `pip` and tried running `ide.extract_image()` on a microscopy image.
I get the error `numpy.AxisError: axis 3 is out of bounds for array of dimension 3`.
Any help/suggestions would be appreciated, thanks!

**Comment by aksub99** [comment]
```
Scale and particle detection begun on: 10.1007-s10008-015-2924-6_2bef222b400c65c998e498ca36b875b1a5afe38e.2.jpg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/imagedataextractor/extract.py", line 248, in extract_images
    filteredvertices, scale, inverted, conversion = main_detection(imgname, imgoutputdir)
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/imagedataextractor/extract.py", line 38, in main_detection
    scale, inlaycoords, conversion = scalebar_identification(img, outputpath, testing = imgname)
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/imagedataextractor/scalebar_identification.py", line 34, in scalebar_identification
    scalebar, scalevalue, conversion, inlaycoords = detect_scale_bar_and_inlays(gimg, imgmean,
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/imagedataextractor/scale_reading.py", line 113, in detect_scale_bar_and_inlays
    scalebar, scalevalue, conversion, inlaycoords = find_text_and_bar(thresholdedimg, gimg, rows, cols, show=show, printer=show)
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/imagedataextractor/scale_reading.py", line 237, in find_text_and_bar
    inverted_srcnn = srcnn_predict(inverted, srcnn)
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/imagedataextractor/scale_reading.py", line 129, in srcnn_predict
    image = np.expand_dims(np.expand_dims(image, 3), 0)
  File "<__array_function__ internals>", line 5, in expand_dims
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 597, in expand_dims
    axis = normalize_axis_tuple(axis, out_ndim)
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/numpy/core/numeric.py", line 1358, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/home/akshay/miniconda3/envs/.image/lib/python3.8/site-packages/numpy/core/numeric.py", line 1358, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 3 is out of bounds for array of dimension 3
```

This is the exact error message if it helps.
